[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino

upload_speed = 115200
monitor_speed = 115200

lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    adafruit/DHT sensor library
    LiquidCrystal_I2C 
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7